### ISSUE TITLE
Support for classic

### ISSUE THREAD

**Issue by furtabs** [Christofmeg/IC2X-UU-Matter#1]

**Comment by Christofmeg** [comment]
@EndangeredNayla 
Thanks for the ticket. It had a very vague description. But I figured you meant "Add support for IC2 Classic profile". 
Updated versions should be available on GitHub, CurseForge and Modrinth shortly.

Or if you referred to IC2-Classic, then you can download IC2C UU-Matter instead:
[GitHub](https://github.com/Christofmeg/IC2C-UU-Matter), [CurseForge](https://www.curseforge.com/minecraft/mc-mods/ic2cuumatter) & [Modrinth](https://modrinth.com/mod/ic2cuumatter)

**Comment by furtabs** [comment]
yes i meant the classic profile, sorry for the vague description
